services:
  postgresql:
    image: postgres:16
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    restart: always

networks:
  default:
    driver: bridge
